### PR TITLE
Feature/update deps

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Use latest BLUI

### CODE REVIEW

**Comment by jeffvg** [comment]
missing page templates?

image

**Comment by emclaug2** [comment]
> missing page templates?
> 
> image

Something weird happened; does this happen w/ a new window, incognito?

**Comment by jeffvg** [comment]
> > missing page templates?
> 
> Something weird happened; does this happen w/ a new window, incognito?

yeah weird, after 2 clicks the list displays

image

**Comment by jeffvg** [comment]
> > missing page templates?
> 
> Something weird happened; does this happen w/ a new window, incognito?

incognito it seems to be fine...

**Comment by emclaug2** [comment]
I'm not sure what caused that issue but it wouldn't be introduced by using the latest vs beta; maybe there was some weird url-redirect going on.

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
